---
version: '2.4'
services:
  ruby-server:
    build:
      context: .
      target: ruby-server
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: standardfile
      DB_USERNAME: root
      DB_PASSWORD: secret123
    links:
      - db
    ports:
      - "3000:3000"
  web-app:
    build:
      context: .
      target: web-app
    depends_on:
      - ruby-server
    environment:
      RAILS_ENV: development
      EXTENSIONS_MANAGER_LOCATION: extensions/extensions-manager/dist/index.html
      BATCH_MANAGER_LOCATION: extensions/batch-manager/dist/index.min.html
      SF_DEFAULT_SERVER: http://localhost:3000
    links:
      - ruby-server
    ports:
      - "3001:3001"
  ext-server:
    build:
      context: .
      target: ext-server
    links:
      - web-app
    ports:
      - "8001:8001"
  nginx:
    build:
      context: .
      target: nginx
    links:
      - web-app
    depends_on:
      - web-app
    ports:
      - "80:80"
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret123
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
