---
version: '2.4'

services:
  ruby-server:
    environment:
      RAILS_ENV: production
    restart: always
    volumes:
      - ./public:/data/src/public
  web-app:
    environment:
      RAILS_ENV: production
    restart: always
    volumes:
      - ./public:/data/src/public
  nginx:
    restart: always
    volumes:
      - ./public:/data/src/public
  db:
    restart: always
    environment:
      RAILS_ENV: development
