---
version: '2.4'

x-env: &ENV
  RAILS_ENV: production

services:
  ruby-server:
    environment:
      <<: *ENV
      SECRET_KEY_BASE: "${RUBY_SERVER_SECRET_KEY_BASE}"
    restart: always
    volumes:
      - ruby_server:/usr/src/app
  web-app:
    environment:
      <<: *ENV
      SECRET_KEY_BASE: "${WEB_APP_SECRET_KEY_BASE}"
    restart: always
    volumes:
      - web_app:/usr/src/app
  ext-server:
    volumes:
      - extensions:/usr/src/app
    command: ['/bin/true']
  #nginx:
    #restart: always
    #volumes:
      #- extensions:/usr/src/app
  db:
    restart: always

volumes:
  extensions: {}
  ruby_server: {}
  web_app: {}
